version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: yearly
    timezone: America/Vancouver
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: yearly
  open-pull-requests-limit: 10
